Repository NLog/NLog.WindowsIdentity, pull requests merged in 2025-07, with the labels that each got.

#12 NLog v6 RTM
  README.md
  appveyor.yml
  src/NLog.WindowsIdentity/ImpersonatingTargetWrapper.cs
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog.WindowsIdentity/NativeMethods.cs
  src/NLog.WindowsIdentity/Properties/AssemblyInfo.cs
  tests/NLog.WindowsIdentity.Tests/ImpersonatingTargetWrapperTests.cs
  tests/NLog.WindowsIdentity.Tests/NLog.WindowsIdentity.Tests.csproj
Labels: major version, size/L

#10 Added TargetFramework net8.0-windows
  src/NLog.WindowsIdentity/ImpersonatingTargetWrapper.cs
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
Labels: size/S

#13 Version 6.0.2
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
Labels: size/XS
